[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
addopts = -p no:launch-testing-ros -p no:ament-copyright -p no:ament-flake8 -p no:ament-xmllint -p no:ament-lint -p no:ament-pep257
